# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(1024, 760)
        Admin.setMinimumSize(QtCore.QSize(0, 0))
        Admin.setMaximumSize(QtCore.QSize(99999, 99999))
        self.centralwidget = QtWidgets.QWidget(Admin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        Admin.setCentralWidget(self.centralwidget)
        self.exportLogAction = QtWidgets.QAction(Admin)
        self.exportLogAction.setObjectName("exportLogAction")
        self.aboutAction = QtWidgets.QAction(Admin)
        self.aboutAction.setObjectName("aboutAction")

        self.retranslateUi(Admin)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Admin)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "管理员页面"))
        self.exportLogAction.setText(_translate("Admin", "导出日志"))
        self.aboutAction.setText(_translate("Admin", "关于"))
