# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Class(object):
    def setupUi(self, Class):
        Class.setObjectName("Class")
        Class.resize(662, 593)
        self.gridLayout_2 = QtWidgets.QGridLayout(Class)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_add = QtWidgets.QPushButton(Class)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout_2.addWidget(self.pushButton_add, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.pushButton_show = QtWidgets.QPushButton(Class)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_show.setFont(font)
        self.pushButton_show.setObjectName("pushButton_show")
        self.gridLayout_2.addWidget(self.pushButton_show, 1, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Class)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Class)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Class)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_className = QtWidgets.QLineEdit(Class)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_className.setFont(font)
        self.lineEdit_className.setObjectName("lineEdit_className")
        self.gridLayout.addWidget(self.lineEdit_className, 0, 1, 1, 1)
        self.lineEdit_num = QtWidgets.QLineEdit(Class)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_num.setFont(font)
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.gridLayout.addWidget(self.lineEdit_num, 2, 1, 1, 1)
        self.lineEdit_classId = QtWidgets.QLineEdit(Class)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_classId.setFont(font)
        self.lineEdit_classId.setObjectName("lineEdit_classId")
        self.gridLayout.addWidget(self.lineEdit_classId, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)

        self.retranslateUi(Class)
        QtCore.QMetaObject.connectSlotsByName(Class)

    def retranslateUi(self, Class):
        _translate = QtCore.QCoreApplication.translate
        Class.setWindowTitle(_translate("Class", "Form"))
        self.pushButton_add.setText(_translate("Class", "添加班级"))
        self.pushButton_show.setText(_translate("Class", "查看班级"))
        self.label_3.setText(_translate("Class", "班级人数："))
        self.label_2.setText(_translate("Class", "班级编号："))
        self.label.setText(_translate("Class", "所带班级："))
