# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_signmanager.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SignManager(object):
    def setupUi(self, SignManager):
        SignManager.setObjectName("SignManager")
        SignManager.resize(934, 553)
        SignManager.setStyleSheet("font: 75 16pt \"Aharoni\";")
        self.gridLayout = QtWidgets.QGridLayout(SignManager)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_clear = QtWidgets.QPushButton(SignManager)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_clear.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_5.addWidget(self.pushButton_clear)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(SignManager)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_export = QtWidgets.QPushButton(SignManager)
        self.pushButton_export.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_export.setObjectName("pushButton_export")
        self.horizontalLayout_6.addWidget(self.pushButton_export)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(SignManager)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SignManager)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_id = QtWidgets.QLineEdit(SignManager)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout.addWidget(self.lineEdit_id)
        self.pushButton_select_id = QtWidgets.QPushButton(SignManager)
        self.pushButton_select_id.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_select_id.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_select_id.setObjectName("pushButton_select_id")
        self.horizontalLayout.addWidget(self.pushButton_select_id)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(SignManager)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(SignManager)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateEdit = QtWidgets.QDateEdit(SignManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.pushButton_select_time = QtWidgets.QPushButton(SignManager)
        self.pushButton_select_time.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_select_time.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_select_time.setObjectName("pushButton_select_time")
        self.horizontalLayout_2.addWidget(self.pushButton_select_time)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(SignManager)
        QtCore.QMetaObject.connectSlotsByName(SignManager)

    def retranslateUi(self, SignManager):
        _translate = QtCore.QCoreApplication.translate
        SignManager.setWindowTitle(_translate("SignManager", "Form"))
        self.pushButton_clear.setText(_translate("SignManager", "清除查询条件"))
        self.pushButton_export.setText(_translate("SignManager", "导出"))
        self.label_2.setText(_translate("SignManager", "按学号查询："))
        self.label.setText(_translate("SignManager", "学号："))
        self.pushButton_select_id.setText(_translate("SignManager", "查询"))
        self.label_3.setText(_translate("SignManager", "按时间查询："))
        self.label_4.setText(_translate("SignManager", "时间："))
        self.pushButton_select_time.setText(_translate("SignManager", "查询"))

